COMMON: &COMMON
  author: "Takayuki, Hara"
  logo:
    source: ""
    width: 100
    height: 100

development:
  hoge: "dev"
  <<: *COMMON

test:
  hoge: "test"
  <<: *COMMON

production:
  hoge: "pro"
  <<: *COMMON
